/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "api4be11295",
            "endpoint": "https://4ric0xxwff.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:2c13f267-d2f1-471c-9a65-9e68a951c996",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1UQq1j667",
    "aws_user_pools_web_client_id": "19q0djkoo4aqijqpt75fdl55hi",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "FAMILY_NAME",
        "GIVEN_NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "reactserverlessappaw1ba327e4a4b74278a50f77c2224120340-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
